export const categories = {
  en: {
    Beverages: [
      "Sweet beverages",
      "Milk based beverages",
      "Juice",
      "Water & plain coffee/tea",
    ],
    Vegetables: ["Vegetables"],
    "Fats, oils & nuts": [
      "Nuts, seeds & oleiferous fruits",
      "Fats & oils",
      "Cream",
    ],
    "Dairy products & Alternatives": [
      "Cheese & cheese products",
      "Fresh and spreadable cheese",
      "Milk & milk alternatives",
      "Yoghurt & curd",
    ],
    Snacks: ["Sweet snacks", "Salty snacks"],
    Excluded: [
      "Alcoholic beverages",
      "Supplements & Special foods",
      "Ingredients",
      "Other",
    ],
    "Grain products & potatoes": [
      "Bread",
      "Dough & flour",
      "Pasta",
      "Breakfast cereals",
      "Potatoes and tubers",
      "Rice & grains",
    ],
    "Meat, fish & eggs": [
      "Meat products & sausages",
      "Fish & seafood",
      "Eggs",
      "Meat & poultry",
    ],
    "Ready-to-eat": ["Add-ons", "Desserts", "Savoury dishes", "Sweet dishes"],
    "Plant based protein": ["Legumes", "Meat & Fish alternatives"],
    Fruits: ["Fruits"],
  },
  de: {
    Getränke: ["Süssgetränke", "Milchgetränke", "Saft", "Wasser, Kaffee & Tee"],
    Gemüse: ["Gemüse"],
    "Fett, Öle & Nüsse": ["Nüsse, Samen & Ölfrüchte", "Fette & Öle", "Rahm"],
    "Milchprodukte & Alternativen": [
      "Käse & Käseprodukte",
      "Frisch- & Streichkäse",
      "Milch & Milchalternativen",
      "Joghurt & Quark",
    ],
    Snacks: ["Süsse Snacks", "Salzige Snacks"],
    Ausgeschlossen: [
      "Alkoholische Getränke",
      "Supplemente & Spezialnahrungsmittel",
      "Zutaten",
      "Andere",
    ],
    "Getreideprodukte & Kartoffeln": [
      "Brot",
      "Teige & Mehl",
      "Pasta",
      "Frühstückscerealien",
      "Kartoffeln & Knollen",
      "Reis & Getreide",
    ],
    "Fleisch, Fisch & Eier": [
      "Fleischprodukte & Wurst",
      "Fisch & Meeresfrüchte",
      "Eier",
      "Fleisch & Geflügel",
    ],
    Fertiggerichte: [
      "Add-ons",
      "Desserts",
      "Herzhafte Gerichte",
      "Süsse Gerichte",
    ],
    "Pflanzliche Proteinquellen": [
      "Hülsenfrüchte",
      "Fleisch- & Fischalternativen",
    ],
    Früchte: ["Früchte"],
  },
};
